name: "bow"
max_speed: 1.0
min_speed: 0.0
max_yawrate: 0.6981
max_accel: 0.2
max_dyawrate: 2.0472

dt: 0.1
predict_time: 3.0 #1.85

goal_radius: 0.3
robot_radius: 0.345
obstacle_length: 0.25
v_reso: 0.01
yawrate_reso: 0.001745329

to_goal_cost_gain: 0.15
to_obstacle_cost_gain: 1.0
speed_cost_gain: 1.0

