name: "dwa"
dt: 0.1
goal_radius: 0.3
horizon: 50
max_accel: 0.2
max_dyawrate: 2.0472
max_speed: 1.0
max_yaw_rate: 0.6981
min_speed: 0.0
max_delta_yaw_rate: 0.6981
v_resolution: 0.014
yaw_rate_resolution: 0.001745333
num_samples: 1000
obstacle_length: 0.25
predict_time: 3.0
robot_radius: 0.38
speed_cost_gain: 1.0
to_goal_cost_gain: 0.15
obstacle_cost_gain: 1.0
v_reso: 0.01
robot_stuck_flag_cons: 0.001
robot_type: "rectangle"
